spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.109/zzwc_cms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: zzwc_cms
        password: 123456
logging:
    config: classpath:logback_dev.xml